---
- name: "[RHPAM] set service account to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: '{{ service_account_name }}'
        namespace: '{{ namespace }}'
        labels:
          application: '{{ application_name }}'

- name: "[RHPAM] set role binding to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: '{{ service_account_name }}-edit'
        namespace: '{{ namespace }}'
        labels:
          application: '{{ application_name }}'
      subjects:
        - kind: ServiceAccount
          name: '{{ service_account_name }}'
      roleRef:
        kind: ClusterRole
        name: edit
