---
businesscentral_image_name: rhpam72-businesscentral-openshift
businesscentral_image_tag: "{{ image_stream_tag }}"
businesscentral_image_namespace: "{{ image_stream_namespace }}"

businesscentral_default_secret_name: "{{ application_name }}-rhpamcentr"
businesscentral_image_pull_policy: IfNotPresent

# Business Central configurable parameters
businesscentral_deployment_name: "{{ application_name }}-rhpamcentr"
businesscentral_service_name: "rhpam-businesscentral"
businesscentral_hostname: "{{ apb_businesscentral_hostname | default('', true) | trim }}"
businesscentral_volume_size: "{{ apb_businesscentral_volume_size | default('', true) | trim }}"
businesscentral_limits_memory: "2Gi"
businesscentral_secret_name: "{{ apb_businesscentral_secret_name | default('', true) | trim }}"
businesscentral_keystore_name: "{{ apb_businesscentral_keystore_name | default('keystore.jks', true) | trim }}"
businesscentral_keystore_alias: "{{ apb_businesscentral_keystore_alias | default('jboss', true) | trim }}"
businesscentral_keystore_pwd: "{{ apb_businesscentral_keystore_pwd | default(lookup('password', tmp_folder + '/keystore_pwd chars=ascii_letters,digits length=8'), true) }}"

# SSO Integration
businesscentral_sso_client: "{{ apb_sso_businesscentral_client | default('', true) | trim }}"
businesscentral_sso_client_secret: "{{ apb_sso_businesscentral_client_secret | default('', true) | trim }}"

# Git Hooks dir
git_hooks_dir: "{{ apb_git_hooks_dir | default('', true) | trim }}"